### ISSUE TITLE
incorrectly implements interface 'IEnumerable<T>'.   Types of property 'constructor' are incompatible.

### ISSUE THREAD

**Issue by manojkgarg2019** [aurigma/DesignAtomsSamples#2]
I have downloaded this project.
Upgraded framework to .net 4.7.2 and typescript 3.7.5.

I am not able to compile. I am getting following error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2420	(TS) Class 'Collection<T>' incorrectly implements interface 'IEnumerable<T>'.
  Types of property 'constructor' are incompatible.
    Type 'Function' is not assignable to type '(getEnumerator: () => IEnumerator<T>) => IEnumerable<T>'.
      Type 'Function' provides no match for the signature '(getEnumerator: () => IEnumerator<T>): IEnumerable<T>'.	C:\GitHub\DesignAtomsSamples\Aurigma.DesignAtoms.Samples (tsconfig or jsconfig project)	C:\GitHub\DesignAtomsSamples\Aurigma.DesignAtoms.Samples\node_modules\@aurigma\design-atoms\Collection.d.ts	6	Active
`

**Comment by asimontsev** [comment]
Not so far ago we have updated Design Atoms (and the sample project). Now it should be compatible with TypeScript 3.7.
